# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('blood_group', models.CharField(max_length=10, verbose_name='Blood Group')),
                ('emergency_contact_1_name', models.CharField(max_length=120, verbose_name='Emergency Contact Name')),
                ('emergency_contact_1_rel', models.CharField(max_length=120, verbose_name='Relation')),
                ('emergency_contact_1_contact_1', models.CharField(max_length=15, verbose_name='Emergency Contact Phone Number 1')),
                ('emergency_contact_1_contact_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact Phone Number 2')),
                ('emergency_contact_2_name', models.CharField(max_length=120, verbose_name='Emergency Contact Name')),
                ('emergency_contact_2_rel', models.CharField(max_length=120, verbose_name='Relation')),
                ('emergency_contact_2_contact_1', models.CharField(max_length=15, verbose_name='Emergency Contact Phone Number 1')),
                ('emergency_contact_2_contact_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact Phone Number 2')),
            ],
            options={
                'verbose_name': 'data',
            },
        ),
    ]
